pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build') {
      steps {
        sh '''#!/bin/bash -l
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
        '''
      }
    }
    stage('Unit Test') {
      steps {
        sh '''#!/bin/bash -l
        . venv/bin/activate
        python3 -m unittest
        '''
      }
    }
  }
}
