pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build') {
      steps {
        sh '''#!/bin/bash -l
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
        '''
      }
    }
    stage('Unit Test') {
      steps {
        sh '''#!/bin/bash -l
        . venv/bin/activate
        python3 -m unittest
        '''
      }
    }
    stage('Build Image') {
      steps {
        sh 'packer build pipeline/packer/ulsahpy.pkr.hcl > packer.txt'
        sh 'awk \'/AMIs were created:/{getline;print;}\' packer.txt | grep -E -o \'ami-[0-9a-z]{17}\' > aws_image.txt'
      }
    }
    stage('Create Instance') {
      steps {
        sh 'bash pipeline/testing/tf_testing.sh'
      }
    }
    stage('Test and destroy the instance') {
      steps {
        sh '''#!/bin/bash -l
        curl --fail \$(<ec2_ip.txt):8081/healthy
        curl -D - -v \$(<ec2_ip.txt):8081/?edition=5 | grep "HTTP/1.1 200" 
        curl -D - -v \$(<ec2_ip.txt):8081/?edition=6 | grep "HTTP/1.1 404"
        cd pipeline/testing
        terraform destroy -var aws_image=\$(<aws_image.txt) -auto-approve
        '''
      }
    }
    stage('Create LB') {
      steps {
        sh 'bash pipeline/production/tf_prod.sh'
      }
    }
  }
  post {
    always {
      archiveArtifacts artifacts: 'packer.txt,aws_image.txt,elb_dnsname.txt,pipeline/production/terraform.tfstate', fingerprint: true
    }
  }
}
