pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build') {
      steps {
        sh '''#!/bin/bash -l
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
        '''
      }
    }
    stage('Unit Test') {
      steps {
        sh '''#!/bin/bash -l
        . venv/bin/activate
        python3 -m unittest
        '''
      }
    }
    stage('Build Image') {
      steps {
        sh 'packer build pipeline/packer/ulsahpy.pkr.hcl > packer.txt'
        sh 'awk \'/AMIs were created:/{getline;print;}\' packer.txt | grep -E -o \'ami-[0-9a-z]{17}\' > aws_image.txt'
      }
    }
  }
  post {
    always {
      archiveArtifacts artifacts: 'packer.txt,aws_image.txt', fingerprint: true
    }
  }
}
